Part-I Numpy Questions
Objective:
To build a strong foundation in using NumPy for numerical computations,
including creating arrays, performing operations, and leveraging its
powerful functionalities.

Task 1: Creating Arrays
1. Write a Python program to:
--> Create a 1D NumPy array of 10 integers ranging from 1 to 10.
--> Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
--> Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
2. Display the shape, size, and datatype of each array

In [7]:
import numpy as np
l1=np.random.randint(1,11,10)
print(l1.shape)
print(l1.size)
print(type(l1))
l1


(10,)
10
<class 'numpy.ndarray'>


array([1, 3, 6, 3, 9, 6, 4, 9, 3, 9], dtype=int32)

In [9]:
import numpy as np
l2=np.random.randint(1,10,9).reshape(3,3)
print(l2.shape)
print(l2.size)
print(type(l2))
l2

(3, 3)
9
<class 'numpy.ndarray'>


array([[2, 8, 5],
       [1, 5, 4],
       [8, 5, 7]], dtype=int32)

In [13]:
import numpy as np
l3=np.random.rand(3,5,3)
print(l3.shape)
print(l3.size)
print(type(l3))
l3

(3, 5, 3)
45
<class 'numpy.ndarray'>


array([[[0.20944813, 0.1141704 , 0.33900474],
        [0.54156809, 0.77270845, 0.45054271],
        [0.39776692, 0.1799548 , 0.05853813],
        [0.63438989, 0.41184282, 0.40815208],
        [0.76736878, 0.49996463, 0.94202117]],

       [[0.4741844 , 0.70248061, 0.2414695 ],
        [0.59260942, 0.69936831, 0.49976674],
        [0.85876242, 0.18048776, 0.09070577],
        [0.83280531, 0.01062013, 0.60703839],
        [0.46561512, 0.44748443, 0.06638304]],

       [[0.61275257, 0.28598363, 0.72974437],
        [0.12026133, 0.31520549, 0.36639818],
        [0.18758917, 0.38782425, 0.19296345],
        [0.50659899, 0.13068912, 0.17745502],
        [0.54281253, 0.74151839, 0.32675268]]])

Task 2: Array Indexing and Slicing:-

1. Create a NumPy array from the following list:
-->data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
2. Write a Python program to:
-->Retrieve the first three elements of the array.
-->Retrieve every alternate element of the array.
-->Reverse the array.
3. Perform the above operations and display the results

In [1]:
import numpy as np
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l1=np.array(data)
print(l1[0:3])
print(l1[::2])
print(l1[::-1])


[1 2 3]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]


Task 3: Mathematical Operations:-
1. Create two NumPy arrays, A and B, each with 5 random integers between 1 and 20.

2. Write a Python program to:-

--> Add, subtract, multiply, and divide the two arrays element-wise.
--> Compute the dot product of the arrays.
--> Find the mean, median, standard deviation, and variance o--> array A.
--> Identify the maximum and minimum values in array B and their indices

In [2]:
# Add, subtract, multiply, and divide the two arrays element-wise.
import numpy as np
A=np.random.randint(2, 20, 10)
B=np.random.randint(2,20,10)
print(A)
print(B)
add=A+B
sub=A-B
mul=A*B
div=A/B
print("Addition :",add)
print("Subtraction :",sub)
print("Multiplication :",mul)
print("Division:",div)

[ 4  4  9 19 18  6  6 16  6  4]
[ 6  6 12  6 15  8 12  8  4 18]
Addition : [10 10 21 25 33 14 18 24 10 22]
Subtraction : [ -2  -2  -3  13   3  -2  -6   8   2 -14]
Multiplication : [ 24  24 108 114 270  48  72 128  24  72]
Division: [0.66666667 0.66666667 0.75       3.16666667 1.2        0.75
 0.5        2.         1.5        0.22222222]


In [3]:
# Compute the dot product of the arrays.
A=np.random.randint(2,20,10)
B=np.random.randint(2,20,10)
print(A)
print(B)
dot_product = np.dot(A, B)
# Or alternatively:
# dot_product = A @ B
print(dot_product)


[18 12  3 11  3 18 19 15  4 11]
[14  2 19  5  7  2 13  3  2  2]
767


In [4]:
# Find the mean, median, standard deviation, and variance o--> array A.
A=np.random.randint(2,20,10)
B=np.random.randint(2,20,10)
print(A)
print("Mean :",np.mean(A))
print("Median :",np.median(A))
print("Standard deviation :",np.std(A))
print("Varience :",np.var(A))


[ 2 14 19  2  5  7 10  4  3 17]
Mean : 8.3
Median : 6.0
Standard deviation : 6.034069936618237
Varience : 36.41000000000001


In [5]:
# Identify the maximum and minimum values in array B and their indices
A=np.random.randint(2,20,10)
B=np.random.randint(2,20,10)
print(B)
print("Maximum :",np.max(B))
print("Minimum :",np.min(B))
print("Maximum idx :",np.argmax(B))
print("Minimum idx :",np.argmin(B))

[13  6 19  7 10  9 18  7  5 18]
Maximum : 19
Minimum : 5
Maximum idx : 2
Minimum idx : 8


Task 4: Reshaping and Transposing
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
2. Write a Python program to:
-->Reshape the array into a 2D array of shape (4, 3).
-->Reshape the array into a 3D array of shape (2, 2, 3).
-->Transpose the reshaped 2D array and display its shape.

In [9]:
import numpy as np

l1 = np.random.randint(1, 12, 12)
print("Original 1D Array:")
print(l1)

print("\n2D Array of Size 4x3:")
print(l1.reshape(4, 3))

print("\n3D Array of Size 2x2x3:")
print(l1.reshape(2, 2, 3))

print("\nTranspose of 2D Array:")
print(np.transpose(l1.reshape(4, 3)))

print("\nShape of Transposed 2D Array:")
print(np.transpose(l1.reshape(4, 3)).shape)


Original 1D Array:
[ 2  3  5  8  7 11  6  9  4  1  1  6]

2D Array of Size 4x3:
[[ 2  3  5]
 [ 8  7 11]
 [ 6  9  4]
 [ 1  1  6]]

3D Array of Size 2x2x3:
[[[ 2  3  5]
  [ 8  7 11]]

 [[ 6  9  4]
  [ 1  1  6]]]

Transpose of 2D Array:
[[ 2  8  6  1]
 [ 3  7  9  1]
 [ 5 11  4  6]]

Shape of Transposed 2D Array:
(3, 4)


Task 5: Boolean Masking and Filtering:-

1. Create a NumPy array with 15 random integers between 10 and 50.
2. Write a Python program to:
-->Find all elements greater than 25.
-->Replace all elements less than 30 with 0.
-->Count the number of elements divisible by 5.

In [10]:
import numpy as np

l2 = np.random.randint(10, 50, 15)
print(l2)

print("Numbers Greater than 25:")
print(l2[l2 > 25])

print("Replacing all elements less than 30 with 0:")
l2[l2 < 30] = 0
print(l2)

print("Number of non-zero elements divisible by 5:")
print(np.count_nonzero(l2[l2 % 5 == 0]))

print("Total number of elements divisible by 5:")
print(np.count_nonzero(l2 % 5 == 0))


[12 43 42 19 43 18 47 34 32 20 43 41 20 42 40]
Numbers Greater than 25:
[43 42 43 47 34 32 43 41 42 40]
Replacing all elements less than 30 with 0:
[ 0 43 42  0 43  0 47 34 32  0 43 41  0 42 40]
Number of non-zero elements divisible by 5:
1
Total number of elements divisible by 5:
6


Task 6: Working with Built-in Functions:-

1. Use NumPy's built-in functions to:
-->Create an array of 10 equally spaced values between 0 and 1.
-->Create an identity matrix of size 4x4.
-->Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

In [11]:
import numpy as np

l1 = np.linspace(0, 1, 10)
print("Array of 10 equally spaced values between 0 and 1:\n")
print(l1)


Array of 10 equally spaced values between 0 and 1:

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
# Create an identity matrix of size 4x4.
import numpy as np
print(np.eye(4,dtype="int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [77]:
# Generate a 1D array of 20 random integers between 1 and 100, sort it, and find the 5 largest elements.

import numpy as np
l3=np.random.randint(1,100,20)
print("Original Array :-")
print(l3)
print("Sorted Array :-")
print(np.sort(l3))
print("5 largest elements")
print(np.sort(l3)[-5:][::-1])

Original Array :-
[90 44 21  1 43 16 12 64 48 33 10 75 63 15 48 44 47 64 58 63]
Sorted Array :-
[ 1 10 12 15 16 21 33 43 44 44 47 48 48 58 63 63 64 64 75 90]
5 largest elements
[90 75 64 64 63]


Task 7: Generic:-

1. Create a Python program that:
-->Generates two large random arrays of size (100, 100).
-->Performs matrix multiplication on the two arrays.
-->Finds the determinant and inverse of the resulting matrix (if possible).
-->Measures the time taken to complete these operations.

In [13]:
import numpy as np
import time

# Step 1: Generate two random 100x100 arrays
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Step 2: Start the timer
start_time = time.time()
print(f"Operation Start time :{start_time} \n")

# Step 3: Matrix multiplication
C = np.dot(A, B)
print("Matrix multiplication completed.\n")
print(C,"\n")


# Step 4: Calculate determinant
det_C = np.linalg.det(C)
print(f"Determinant of the result: {det_C} \n")


# Step 5: Try to calculate inverse if determinant is not zero
if np.isclose(det_C, 0):
    inverse_C = None
    invertible = False
else:
    inverse_C = np.linalg.inv(C)
    invertible = True

# Step 6: End the timer
end_time = time.time()
print(f"Operation end time :{end_time} \n")

elapsed_time = end_time - start_time

# Step 7: Print results
print("Matrix is invertible." if invertible else "Matrix is not invertible.")
if invertible:
    print("Inverse matrix calculated successfully.")
    print(inverse_C,"\n")
print(f"Time taken: {elapsed_time:.4f} seconds")


Operation Start time :1752414340.1146615 

Matrix multiplication completed.

[[28.82432265 24.9077027  24.105488   ... 25.32605882 24.53292793
  25.03957562]
 [29.22827896 26.909049   25.40053007 ... 24.93425135 26.90837035
  24.38075666]
 [29.81268261 25.58480117 25.47037416 ... 27.16724325 26.36240604
  25.05030823]
 ...
 [29.58187622 27.10769114 25.06662913 ... 25.01497412 23.52483332
  24.95272635]
 [28.73813533 25.08545973 25.13237977 ... 24.74231819 24.22764661
  25.61301863]
 [26.0106899  22.42449126 23.28411581 ... 23.52377361 23.0428638
  21.47837486]] 

Determinant of the result: 7.202465595419879e+49 

Operation end time :1752414340.1601465 

Matrix is invertible.
Inverse matrix calculated successfully.
[[-0.19877882 -1.86883537 -1.88653425 ... -1.03477222  3.44450906
  -2.50097038]
 [-0.93214949 -1.48875617 -0.88726987 ... -1.09671465  1.93855582
  -1.44226878]
 [ 0.26060437 -0.31328886 -1.427215   ... -2.50400177  5.41388522
  -5.0447201 ]
 ...
 [-0.36083237 -0.30247616 -0